version: "3.9"

services:
  db:
    image: postgres:13.1
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - db-data:/var/lib/postgresql/data
  bookstore:
    build:
      context: .
      dockerfile: Dockerfile.local
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db-data:
    driver: local
